from enum import StrEnum


class ReasonCode(StrEnum):
    EXACT_STUDENT_ID = "EXACT_STUDENT_ID"
    SINGLE_GUARDIAN_STUDENT = "SINGLE_GUARDIAN_STUDENT"
    EXACT_OUTSTANDING_BALANCE = "EXACT_OUTSTANDING_BALANCE"
    KNOWN_PAYER_MAPPING = "KNOWN_PAYER_MAPPING"
    DUPLICATE_REFERENCE = "DUPLICATE_REFERENCE"
    AMBIGUOUS_CANDIDATES = "AMBIGUOUS_CANDIDATES"
    NO_CANDIDATE = "NO_CANDIDATE"
    PROMPT_BUDGET_EXCEEDED = "PROMPT_BUDGET_EXCEEDED"
    INFERENCE_UNAVAILABLE = "INFERENCE_UNAVAILABLE"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    MODEL_RANKED = "MODEL_RANKED"
    MODEL_ABSTAINED = "MODEL_ABSTAINED"
